# Default values for bonus.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

clientName: "bonus"

images:
  php:
    repository: 415336189928.dkr.ecr.eu-central-1.amazonaws.com/app
    tag: latest
    pullPolicy: IfNotPresent
  nginx:
    repository: nginx
    tag: stable
    pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  path: /
  host: demo2.cluster.arts-digital.ru
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources:
  nginx:
    requests:
      cpu: 10m
      memory: 64Mi
    limits:
      cpu: 100m
      memory: 128Mi
  php:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 300m
      memory: 256Mi
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.


nodeSelector: {}

tolerations: []

affinity: {}

mysql:
#  database: ""
#  user: ""
  password: cGFzcw==


