apiVersion: v1
kind: ConfigMap
metadata:
    name: {{ .Values.clientName }}-nginx-config
data:
    nginx.conf: |
        worker_processes auto;
        events {
            worker_connections  1024;
        }

        http {
            include      /etc/nginx/mime.types;
            default_type application/octet-stream;
            gzip on;
            gzip_http_version 1.0;
            gzip_comp_level 2;
            gzip_proxied any;
            gzip_vary off;
            gzip_types text/plain text/css application/x-javascript text/xml application/xml application/rss+xml application/atom+xml text/javascript application/javascript application/json text/mathml;
            gzip_min_length  1000;
            gzip_disable "MSIE [1-6]\.";

            server {
                listen 80;

                root /codebase/public;

                index index.html index.htm index.php;

                server_name _;

                charset utf-8;

                location = /favicon.ico { log_not_found off; access_log off; }
                location = /robots.txt { log_not_found off; access_log off; }

                location / {
                    try_files $uri $uri/ /index.php$is_args$args;
                }

                location ~ \.php$ {
                    fastcgi_split_path_info ^(.+\.php)(/.+)$;
                    fastcgi_pass php:9000;
                    fastcgi_index index.php;
                    include fastcgi_params;
                    fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
                    fastcgi_param PATH_INFO $fastcgi_path_info;
                }

                error_page 404 /index.php;

                location ~ /\.ht {
                    deny all;
                }
            }
        }


