{{/*{{- if .Values.ingress.enabled -}}*/}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Values.clientName }}
  labels:
    application: demo
    client: {{ .Values.clientName }}
spec:
  rules:
    - host: {{ .Values.ingress.host}}
      http:
        paths:
          - backend:
              serviceName: {{ .Values.clientName }}
              servicePort: http
