apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.clientName }}
  labels:
    application: {{ .Values.clientName }}
    version: v1
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    tier: app
